basePath: /
definitions:
  entities.Atraccion:
    properties:
      enviado:
        type: boolean
      fecha:
        type: string
      hora:
        type: string
      nombre:
        type: string
      tiempo:
        type: integer
      zona:
        description: Nuevo campo
        type: string
    type: object
  entities.Visitas:
    properties:
      enviado:
        type: boolean
      fecha:
        type: string
      hora:
        type: string
      visitantes:
        type: integer
      zona:
        description: Nuevo campo
        type: string
    type: object
host: localhost:8080
info:
  description: API para registrar y consultar atracciones y visitas, integradas con
    RabbitMQ.
  title: API de Atracciones y Visitas
  version: "1.0"
paths:
  /atracciones:
    post:
      consumes:
      - application/json
      description: Crea atracciones en la base de datos y las envía a RabbitMQ si
        es posible
      parameters:
      - description: Arreglo de atracciones o una sola atracción
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.Atraccion'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/entities.Atraccion'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Crear una o varias atracciones
      tags:
      - atracciones
  /atracciones/dia:
    get:
      description: A partir de una fecha especificada envía los datos que no se pudieron enviar anteriormente a RabbitMQ y las vuelve a enviar
      parameters:
      - description: Fecha desde la cual obtener atracciones (YYYY-MM-DD) SOLO PARA EMERGENCIA
        in: query
        name: fecha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Atraccion'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener atracciones desde una fecha
      tags:
      - atracciones
  /visitas:
    post:
      consumes:
      - application/json
      description: Crea visitas en la base de datos y las envía a RabbitMQ si es posible
      parameters:
      - description: Arreglo de visitas o una sola visita
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.Visitas'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/entities.Visitas'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Crear una o varias visitas
      tags:
      - visitas
  /visitas/dia:
    get:
      description: A partir de una fecha especificada envía los datos que no se pudieron enviar anteriormente a RabbitMQ y las vuelve a enviar
      parameters:
      - description: Fecha desde la cual obtener visitas (YYYY-MM-DD) SOLO PARA EMERGENCIA
        name: fecha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Visitas'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener visitas desde una fecha
      tags:
      - visitas
swagger: "2.0"
