basePath: /api
definitions:
  entities.Atraccion:
    properties:
      enviado:
        type: boolean
      fecha:
        type: string
      hora:
        type: string
      id:
        type: integer
      nombre:
        type: string
      tiempo:
        type: integer
      zona:
        type: string
    type: object
  entities.VisitaGeneral:
    properties:
      fecha:
        type: string
      id:
        type: integer
      visitas:
        type: integer
    type: object
  entities.Visitas:
    properties:
      enviado:
        type: boolean
      fecha:
        type: string
      hora:
        type: string
      id:
        type: integer
      visitantes:
        type: integer
      zona:
        type: string
    type: object
info:
  contact: {}
  description: API que proporciona datos en tiempo real sobre visitas y atracciones,
    protegida con autenticación por token JWT PARA PODER USAR LOS METODOS SE NECESITARA
    UN TOKEN EL CUAL UNA VEZ OBTENIDO SE INSERTARA EN EL APARTADO DE AUTHORIZE MAS
    ESPECIFICO EL BOTON VERDE DE ABAJO CON UN CANDADO INSERTAR EL TOKEN EN EL APARTADO
    VALUE Y PULSAR EL BOTON DE AUTHORIZE UNA VEZ HECHO ESO DEBERIA DE PODER CERRAR
    LA VENTANA SIN PROBLEMAS Y USAR LOS METODOS DE AHORA EN ADELANTE
  title: API de Monitoreo de Visitas y Atracciones
  version: "1.0"
paths:
  /atraccion/lastweek:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Atraccion'
            type: array
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener atracciones de las 6 fechas más recientes
      tags:
      - atraccion
  /atraccion/now:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Atraccion'
            type: array
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener atracciones de la fecha más reciente
      tags:
      - atraccion
  /atraccion/ojiva:
    get:
      parameters:
      - description: Fecha en formato YYYY-MM-DD
        in: query
        name: fecha
        type: string
      produces:
      - application/json
      responses:
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener ojiva de atracción (tiempo total por hora)
      tags:
      - atraccion
  /atraccion/yesterday:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Atraccion'
            type: array
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener atracciones de la penúltima fecha registrada
      tags:
      - atraccion
  /visitas/lastweek:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Visitas'
            type: array
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener visitas de las 6 fechas más recientes
      tags:
      - visitas
  /visitas/now:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Visitas'
            type: array
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener visitas de la fecha más reciente
      tags:
      - visitas
  /visitas/ojiva:
    get:
      parameters:
      - description: Fecha en formato YYYY-MM-DD
        in: query
        name: fecha
        type: string
      produces:
      - application/json
      responses:
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener ojiva de visitas (suma por hora)
      tags:
      - visitas
  /visitas/yesterday:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Visitas'
            type: array
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener visitas de la penúltima fecha registrada
      tags:
      - visitas
  /visitasgeneral:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.VisitaGeneral'
            type: array
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener todas las visitas registradas
      tags:
      - visitasGeneral
    post:
      consumes:
      - application/json
      parameters:
      - description: Datos de la visita
        in: body
        name: visita
        required: true
        schema:
          $ref: '#/definitions/entities.VisitaGeneral'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Crear una nueva visita
      tags:
      - visitasGeneral
  /visitasgeneral/{fecha}:
    delete:
      parameters:
      - description: Fecha de la visita en formato YYYY-MM-DD
        in: path
        name: fecha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Eliminar una visita por fecha
      tags:
      - visitasGeneral
    get:
      parameters:
      - description: Fecha de la visita en formato YYYY-MM-DD
        in: path
        name: fecha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.VisitaGeneral'
        "401":
          description: Token inválido o no autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Obtener una visita por fecha
      tags:
      - visitasGeneral
    put:
      consumes:
      - application/json
      parameters:
      - description: Fecha de la visita en formato YYYY-MM-DD
        in: path
        name: fecha
        required: true
        type: string
      - description: Nuevos datos de la visita
        in: body
        name: visita
        required: true
        schema:
          $ref: '#/definitions/entities.VisitaGeneral'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Token invál
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWTQuery: []
      summary: Actualizar una visita por fecha
      tags:
      - visitasGeneral
securityDefinitions:
  JWTQuery:
    in: query
    name: token
    type: apiKey
swagger: "2.0"
